### ISSUE TITLE
Issue Loading the conll-formatted-ontonotes-5.0

### ISSUE THREAD

**Issue by ukamath** [sebastianruder/sluice-networks#1]
<img width="1142" alt="screen shot 2017-12-21 at 5 24 18 pm" src="https://user-images.githubusercontent.com/4322740/34277475-e0167fd2-e673-11e7-8b8c-c17f8356a7af.png">

When i run with 
python3 run_sluice_net.py --dynet-autobatch 1 --dynet-seed 123 \
                         --task-names pos ner --h-layers 3  --pred-layer 3 3 \
                         --cross-stitch --layer-connect stitch \
                         --num-subspaces 2 --constraint-weight 0.1 \
                         --constrain-matrices 1 2 --patience 3 \
                         --train-dir conll-formatted-ontonotes-5.0/data/train \
                         --dev-dir conll-formatted-ontonotes-5.0/data/development \
                         --test-dir conll-formatted-ontonotes-5.0/data/test \
                         --train bc --test bn mz nw wb \
                         --model-dir model/pos_3__ner_3bc_mz --log-dir logs
I get the error 

Reading training data from conll-formatted-ontonotes-5.0/data/train...
Traceback (most recent call last):
  File "run_sluice_net.py", line 231, in <module>
    main(args)
  File "run_sluice_net.py", line 119, in main
    train_dir=args.train_dir, dev_dir=args.dev_dir)
  File "/Users/uday.kamath/sluice-networks-master/sluice_net.py", line 264, in fit
    [train_domain], self.task_names, data_dir=train_dir, train=True)
  File "/Users/uday.kamath/sluice-networks-master/utils.py", line 319, in get_data
    '%s.' % domain)
AssertionError: No data read for bc.

**Comment by antgr** [comment]
I just saw that you have opened the same issue. But you closed it. How did you overcome this error?
Edit: see "ontonotes-5.0 format" ticket. (I used a dataset that is not in the correct format.)
